import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/common/layout/Header'
import Footer from '@/components/common/layout/Footer'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='font-base bg-white'>
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  )
}
